spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 879916541121-leive7jg4fqveie1dig511v0tf7mva1o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email