eureka:
  instance:
    instance-id: member-microservice-instance
    appname: member-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka

server:
  port: 8788
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: member-service
    # components:support:swagger
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/syuck_syuck_db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 463afc
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: "SELECT 1"
      test-on-borrow: true
      test-on-return: false
    hikari:
      pool-name: SpringBootJPAHikariCP
      maximum-pool-size: 30
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 28797000 # 480000
  jpa:
    database: mysql
    show-sql: false
    #    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100

