ssh-connection:
  list:
    - session-name: mysql
      privateKey: path
      connection-host: 10.10.10.10
      connection-port: 22
      host: 127.0.0.1
      user-name: root
      password: root
      lport: 13316
      rport: 3306
  schedule:
    ssh-keep-alive: 0 0/3 * * * ?
    ssh-keep-alive-run: true